### ISSUE TITLE
SimpleQuestion dataset download link is broken

### ISSUE THREAD

**Issue by leandroltavares** [karthikncode/nlp-datasets#10]
The dataset (SimpleQuestions) Large-scale Simple Question Answering with Memory Networks, 2015 is broken. The provided link https://www.dropbox.com/s/tohrsllcfy7rch4/SimpleQuestions_v2.tgz is not available

**Comment by markroxor** [comment]
It works for me.

**Comment by leandroltavares** [comment]
It is working for me now!
