### ISSUE TITLE
MCTest data link

### ISSUE THREAD

**Issue by desertnaut** [karthikncode/nlp-datasets#6]
Hi and thanks for this repo!

The data link for MCTest is no longer valid, probably due to some rearranging of MS website; I am trying to locate the dataset itself, have come up with [this repo](https://github.com/mcobzarenco/mctest/tree/master/data/MCTest), but I am not sure if it is the official one.

Any ideas?

**Comment by karthikncode** [comment]
Yes, that looks like the official data. Thanks for the pointer!
